spring:
   datasource:
      url: jdbc:sqlserver://recoletaserver.database.windows.net:1433;database=recoleta-database;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      username: AdminServer
      password: R3col3t@
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: create
         dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
   port: 1433
logging:
   level:
      org.springframework.jdbc.core: DEBUG

   